version: '3.7'

services:
  traefik:
    image: traefik:latest
    ports:
      - "8090:80"
      - "8080:8080"
    volumes:
      - ./:/etc/traefik/
  nginx-1:
    image: nginx:latest
    volumes:
      - ./nginx-1:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
  nginx-2:
    image: nginx:latest
    volumes:
      - ./nginx-2:/usr/share/nginx/html:ro
    ports:
      - "8082:80"
