java:
  image: java:alpine
  volumes:
    - ../build/libs/:/mnt/app/
  command: java -classpath "/mnt/app/*" io.github.picodotdev.blogbitix.cache.Main

nginx:
  image: nginx:alpine
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  links:
    - java
  ports:
    - "80:80"
